// Unit 8: Digital Financial Tools and Applications - Tutorial & Textbook Grade Content
export function getUnit8Content() {
  return {
    unitNumber: 8,
    title: "Digital Financial Tools and Applications",
    officialSection: "8.0 - 8.6",
    totalHours: 8,
    theoryHours: 4,
    practicalHours: 4,
    introduction: "Digital financial tools represent the technological transformation of banking, payments, and currency transfers into secure, instantaneous cashless systems. In India, under the leadership of the Reserve Bank of India (RBI) and the National Payments Corporation of India (NPCI), world-leading platforms have emerged. This unit teaches the operational architecture of digital authentication (OTP, QR Codes), UPI and the BHIM app, AEPS biometric banking, offline USSD banking (*99#), payment cards (Debit, Credit, RuPay), electronic fund transfer mechanisms (NEFT, RTGS, IMPS), BBPS utility bill systems, and critical cyber banking safety rules.",
    whatYouWillLearn: [
      "Digital security authentication: One Time Password (OTP) characteristics and 2D Quick Response (QR) code anatomy.",
      "The Unified Payments Interface (UPI) and BHIM app: Virtual Payment Addresses (VPA), 24x7 real-time settlement, and the golden rule of the UPI PIN (required ONLY to send money, NEVER to receive).",
      "Aadhaar Enabled Payment System (AEPS): 12-digit Aadhaar plus biometric authentication at Micro-ATMs through Bank Mitras.",
      "USSD Banking (*99#): National Unified USSD Platform (NUUP) operating on basic 2G feature phones without an internet connection.",
      "Payment cards: Debit Card (pay now) versus Credit Card (pay later), 16-digit card numbers, 3-digit CVV, and RuPay domestic card network.",
      "Electronic Fund Transfers compared: NEFT (30-minute batches, no minimum), RTGS (Real Time Gross Settlement, minimum ₹2,00,000), and IMPS (instant, 24x7, NPCI).",
      "Bharat Bill Payment System (BBPS) and safe banking rules (National Cyber Helpline 1930)."
    ],
    topics: [
      {
        code: "8.1",
        title: "Digital Authentication: OTP and QR Code",
        whatIsIt: "Digital authentication tools verify a user's identity before authorizing a financial transaction. An **OTP (One Time Password)** is a dynamic, single-use numeric code, while a **QR Code (Quick Response Code)** is a two-dimensional matrix barcode storing encrypted transaction data.",
        whyImportant: "Static passwords can be stolen or guessed. Dynamic OTPs and scanned QR codes prevent unauthorized card usage and eliminate manual entry of bank account numbers.",
        howItWorks: "An OTP is generated by cryptographic algorithms on the bank server and transmitted via SMS, expiring in 5 to 10 minutes. A QR code is captured by an optical camera sensor and decoded in milliseconds by payment apps.",
        tableTitle: "AUTHENTICATION TOOLS SPECIFICATION TABLE",
        table: {
          headers: ["Security Tool", "Inventor & Origin", "Core Structural Architecture", "Key Security Attribute & Expiry"],
          rows: [
            ["OTP (One Time Password)", "Cryptographic Standards (2FA)", "4-digit or 6-digit numeric dynamic security code", "Single-use only; auto-expires in **5 to 10 minutes**; never share with anyone"],
            ["QR Code (Quick Response)", "Denso Wave / Masahiro Hara (1994)", "2D square matrix with **3 distinct corner positioning squares**", "Can be read from any 360° angle; contains up to **30% Reed-Solomon error correction**"],
            ["Bharat QR", "NPCI, Visa, Mastercard (2017)", "Interoperable national digital merchant payment standard", "Enables direct merchant payments without entering account numbers"]
          ],
          colWidths: [120, 130, 140, 121]
        },
        practicalExample: "When you buy an online railway ticket with your debit card: The payment gateway sends a 6-digit OTP to your registered phone. You type the OTP within 5 minutes to authenticate the payment. Even if a fraudster stole your card number, they cannot complete the transaction without that unique SMS OTP.",
        importantPoints: [
          "OTP stands for One Time Password.",
          "An OTP is valid for a single transaction only and expires within 5 to 10 minutes.",
          "QR Code stands for Quick Response Code.",
          "QR Codes were invented by Denso Wave (Masahiro Hara) in 1994.",
          "A standard QR Code features 3 large positioning finder squares in its corners.",
          "QR codes support up to 30% error correction, allowing damaged codes to still be scanned."
        ],
        quickRevision: "OTP = One Time Password (single use, 5-10 min expiry, 2FA). QR Code = Quick Response (Denso Wave 1994, 2D matrix, 3 corner squares, 30% error correction)."
      },
      {
        code: "8.2",
        title: "Unified Payments Interface (UPI) and BHIM",
        whatIsIt: "UPI (Unified Payments Interface) is an advanced real-time payment system developed by the National Payments Corporation of India (NPCI) that powers multiple bank accounts into a single mobile application for 24x7 instant fund transfers.",
        whyImportant: "UPI eliminates the need to remember cumbersome 16-digit bank account numbers and IFSC codes, transforming India into the world's largest digital payments economy.",
        howItWorks: "UPI links a user's mobile number and bank account to a unique **Virtual Payment Address (VPA)** (e.g. `saurabh@upi`). Transactions route through NPCI's switch and settle bank-to-bank instantly.",
        componentsTitle: "CRITICAL UPI CONCEPTS & THE GOLDEN RULE OF UPI PIN",
        componentsOrTypes: [
          "NPCI: National Payments Corporation of India, an initiative of RBI and IBA that developed and manages UPI.",
          "VPA (Virtual Payment Address): A human-friendly financial ID (e.g. `username@bankname`) that masks underlying bank account details.",
          "BHIM App: Bharat Interface for Money, launched by Prime Minister Narendra Modi on **30 December 2016**, named in honor of Dr. B.R. Ambedkar.",
          "UPI 123PAY: NPCI's IVR voice-based payment service enabling UPI transactions on basic 2G feature phones without an internet connection.",
          "CRITICAL EXAM RULE (UPI PIN): The 4-digit or 6-digit UPI PIN is required **ONLY to SEND money or check account balance**. You **NEVER need to enter your UPI PIN to RECEIVE money**."
        ],
        practicalExample: "A fraudster sends a fake 'Cashback of ₹2,000' link and asks you to enter your UPI PIN to receive the money. If you enter your UPI PIN, money is immediately DEBITED from your account! Remember: Entering a UPI PIN always deducts money from your bank.",
        importantPoints: [
          "UPI was developed by NPCI (National Payments Corporation of India).",
          "VPA stands for Virtual Payment Address.",
          "BHIM was launched on 30 December 2016 and is named after Dr. B.R. Ambedkar.",
          "UPI PIN is required ONLY to send money or check balance, NEVER to receive money.",
          "UPI operates 24x7x365 including all bank holidays and weekends."
        ],
        quickRevision: "UPI was developed by NPCI (2016, 24x7). Uses VPA (`name@upi`). BHIM launched 30 Dec 2016. Golden Rule: UPI PIN is entered ONLY to send money, never to receive."
      },
      {
        code: "8.3",
        title: "Aadhaar Enabled Payment System (AEPS)",
        whatIsIt: "AEPS (Aadhaar Enabled Payment System) is a bank-led financial inclusion model developed by NPCI that allows interoperable digital banking transactions at point-of-sale Micro-ATMs using only a customer's 12-digit Aadhaar number and biometric fingerprint or iris authentication.",
        whyImportant: "AEPS brings formal banking to rural villages where physical bank branches and traditional ATMs do not exist, eliminating the need for debit cards, PINs, or smartphones.",
        howItWorks: "A customer visits a local **Bank Mitra (Business Correspondent)** equipped with a handheld Micro-ATM. The customer provides their 12-digit Aadhaar number, selects their bank, and presses their finger onto the biometric scanner. The scanner contacts UIDAI's Aadhaar server to authenticate the customer, and the Bank Mitra hands over physical cash.",
        tableTitle: "CORE BANKING SERVICES PROVIDED BY AEPS",
        table: {
          headers: ["AEPS Financial Service", "Operational Description", "Customer Requirements at Micro-ATM"],
          rows: [
            ["Cash Withdrawal", "Withdraw cash directly from Aadhaar-linked bank account", "12-digit Aadhaar Number + Biometric Fingerprint scan"],
            ["Cash Deposit", "Deposit cash into any Aadhaar-linked bank account", "Aadhaar Number + Cash handed to Bank Mitra"],
            ["Balance Inquiry", "Check real-time available balance on bank account", "Prints balance slip or displays on Micro-ATM screen"],
            ["Mini Statement", "Prints recent 5 to 10 account transactions", "Aadhaar verification via Bank Mitra terminal"],
            ["Aadhaar Pay (Merchant)", "Pay local village merchant directly for groceries", "Customer's biometric fingerprint authorizes payment directly to merchant"]
          ],
          colWidths: [130, 180, 201]
        },
        practicalExample: "A rural pension beneficiary walks to the village Bank Mitra center. Without a debit card or smartphone, they state their bank name, enter their 12-digit Aadhaar number, and place their thumb on the biometric scanner. The system verifies their thumbprint with UIDAI and dispenses their ₹1,500 monthly pension immediately.",
        importantPoints: [
          "AEPS stands for Aadhaar Enabled Payment System.",
          "AEPS transactions require two credentials: 12-digit Aadhaar number and Biometric Authentication (Fingerprint / Iris).",
          "AEPS operates through Business Correspondents (Bank Mitras) using handheld Micro-ATMs.",
          "AEPS requires that the customer's bank account is linked (seeded) with their Aadhaar number."
        ],
        quickRevision: "AEPS (NPCI) provides cardless rural banking via Bank Mitras using a 12-digit Aadhaar number + Biometric fingerprint. Supports cash withdrawal, deposit, and balance checks."
      },
      {
        code: "8.4",
        title: "USSD Banking (*99# NUUP)",
        whatIsIt: "USSD (Unstructured Supplementary Service Data) banking is a GSM telecom-based mobile banking service that operates by dialing **`*99#`** on any mobile phone, allowing users to perform financial transactions on basic 2G feature phones with zero internet connectivity.",
        whyImportant: "Millions of citizens in remote areas use basic non-smart keypad phones (feature phones) with no data connections. USSD banking ensures financial inclusion across 100% of mobile handsets.",
        howItWorks: "USSD uses interactive text-based telecom signalling channels. When a user dials `*99#`, NPCI's National Unified USSD Platform (NUUP) connects the phone to the user's bank menu in real time.",
        componentsTitle: "KEY FEATURES OF *99# USSD BANKING",
        componentsOrTypes: [
          "Universal Service Code: **`*99#`** (dialed like a phone call from the mobile keypad).",
          "Governing Network: Managed by NPCI under the NUUP (National Unified USSD Platform) umbrella.",
          "Zero Internet Requirement: Operates on basic 2G/3G voice signaling; works on any simple feature phone.",
          "Language Support: Available in **13 Indian languages** (e.g. `*99*22#` for Hindi).",
          "MMID (Mobile Money Identifier): A unique **7-digit numeric code** issued by banks to identify a bank account for mobile fund transfers.",
          "Available Services: Fund transfer (via MMID, Account+IFSC, or UPI ID), Balance inquiry, and PIN change."
        ],
        practicalExample: "A user with a basic ₹800 keypad phone wants to check their bank balance: They dial `*99#`, select their bank, and enter their UPI PIN. The screen immediately displays: 'Your balance in A/C XXXX is ₹4,250', with zero data charges and no internet required.",
        importantPoints: [
          "The universal USSD code for mobile banking is `*99#`.",
          "USSD banking does NOT require an internet connection or smartphone.",
          "NUUP stands for National Unified USSD Platform.",
          "MMID (Mobile Money Identifier) consists of exactly 7 digits.",
          "`*99#` services are supported in 13 Indian languages."
        ],
        quickRevision: "USSD banking dials `*99#` (NUUP/NPCI). Works on basic 2G feature phones with NO internet. Uses 7-digit MMID. Available in 13 Indian languages."
      },
      {
        code: "8.5",
        title: "Payment Cards: Debit, Credit, and RuPay",
        whatIsIt: "Payment cards are plastic magnetic-stripe and EMV microchip cards issued by banks allowing customers to make purchases at Point of Sale (PoS) terminals, withdraw cash at ATMs, and pay online.",
        whyImportant: "Payment cards replace physical paper cash, provide fraud protection through chip-and-PIN authentication, and enable global travel and digital commerce.",
        howItWorks: "Cards connect via international (Visa, Mastercard) or domestic (RuPay) payment networks, authorizing debiting from checking accounts or extending revolving credit lines.",
        tableTitle: "DEBIT CARDS VS. CREDIT CARDS VS. RUPAY",
        table: {
          headers: ["Card Concept", "Financial Mechanism", "Key Specifications & Security", "National Strategic Role"],
          rows: [
            ["Debit Card", "'Pay Now' mechanism: Money is debited directly and immediately from user's savings account", "16-digit card number, Expiry Date, 3-digit CVV on back signature strip, 4-digit ATM PIN", "Issued automatically with savings bank accounts; transaction limited to account balance"],
            ["Credit Card", "'Pay Later' mechanism: Bank extends a revolving line of credit; bill paid at month end", "Requires credit score approval; charges interest if monthly balance is not cleared in full", "Offers a 45 to 50 day interest-free credit grace period; provides reward points"],
            ["RuPay Card", "India's indigenous domestic card payment network (Launched 2012 by NPCI)", "Features lower transaction processing fees; operates across ATMs, PoS, and e-commerce", "Empowers financial inclusion; standard card issued under Pradhan Mantri Jan-Dhan Yojana (PMJDY)"]
          ],
          colWidths: [95, 145, 140, 131]
        },
        componentsTitle: "PAYMENT CARD SECURITY & POS TERMINALS",
        componentsOrTypes: [
          "Card Number: 16 digits embossed on the front of the card.",
          "CVV (Card Verification Value): A 3-digit security code printed on the reverse side of the card on the signature strip (never share your CVV with anyone).",
          "EMV Chip & PIN: Gold microchip preventing physical card cloning; requires a 4-digit secret PIN at PoS terminals.",
          "PoS (Point of Sale): Physical electronic card-swipe/insert machines at retail stores; mPoS (mobile PoS) connects via Bluetooth to a smartphone."
        ],
        practicalExample: "When purchasing groceries at a supermarket: You insert your RuPay Debit Card into the merchant's PoS machine. The merchant types ₹1,200. You enter your secret 4-digit ATM PIN on the keypad. The PoS machine communicates with your bank, prints a receipt, and deduces ₹1,200 from your account.",
        importantPoints: [
          "Payment cards contain a 16-digit card number.",
          "CVV stands for Card Verification Value and contains 3 digits on the back of the card.",
          "RuPay is an Indian domestic card network launched in 2012 by NPCI.",
          "RuPay cards are issued to beneficiaries of Pradhan Mantri Jan-Dhan Yojana (PMJDY).",
          "PoS stands for Point of Sale."
        ],
        quickRevision: "Debit Card = pay now from savings. Credit Card = pay later with credit line. 16-digit card number, 3-digit CVV. RuPay is India's domestic card network by NPCI (2012)."
      },
      {
        code: "8.6",
        title: "Electronic Fund Transfer: NEFT, RTGS, and IMPS",
        whatIsIt: "Electronic Fund Transfer (EFT) systems are inter-bank telecommunication networks that move money electronically from one bank account to another across India.",
        whyImportant: "EFT systems eliminate physical paper bank cheques, bank drafts, and postal money orders, processing high-value and retail funds securely 24x7.",
        howItWorks: "Transactions route through central clearing switches managed by the Reserve Bank of India (RBI for NEFT and RTGS) or NPCI (for IMPS).",
        tableTitle: "MASTER COMPARISON: NEFT VS. RTGS VS. IMPS",
        table: {
          headers: ["Attribute / Parameter", "NEFT (National Electronic Funds Transfer)", "RTGS (Real Time Gross Settlement)", "IMPS (Immediate Payment Service)"],
          rows: [
            ["Governing Authority", "Reserve Bank of India (RBI)", "Reserve Bank of India (RBI)", "NPCI (National Payments Corporation of India)"],
            ["Settlement Model", "Half-hourly Net Batch settlement cycles (48 batches daily)", "Continuous Real-Time Gross settlement (Order-by-order)", "Immediate, instant credit within seconds"],
            ["Minimum Transfer Limit", "**No Minimum Limit** (Transfer can start from ₹1)", "**Minimum Limit: ₹2,00,000 (Two Lakh Rupees)**", "**No Minimum Limit** (Transfer can start from ₹1)"],
            ["Maximum Transfer Limit", "No upper ceiling limit set by RBI", "No upper ceiling limit set by RBI", "**Maximum Limit: ₹5,00,000 (Five Lakh Rupees)**"],
            ["Operating Availability", "24x7x365 round-the-clock", "24x7x365 round-the-clock", "24x7x365 round-the-clock"],
            ["Primary Use Case", "General commercial payments, salary credits, vendor bills", "High-value corporate, real-estate, and institutional transfers", "Instant round-the-clock urgent personal money transfers"]
          ],
          colWidths: [110, 130, 135, 136]
        },
        practicalExample: "A businessman buying industrial machinery for ₹5,00,000 uses **RTGS** because the amount exceeds ₹2,00,000 and requires gross settlement. A father sending ₹5,000 urgently to his son at 11 PM on Sunday uses **IMPS** or UPI for instant transfer within 3 seconds.",
        importantPoints: [
          "NEFT stands for National Electronic Funds Transfer (managed by RBI, 30-minute batches).",
          "RTGS stands for Real Time Gross Settlement (managed by RBI).",
          "The MINIMUM transfer limit for RTGS is ₹2,00,000 (Two Lakh Rupees).",
          "IMPS stands for Immediate Payment Service (managed by NPCI, instant transfer up to ₹5 Lakh).",
          "NEFT, RTGS, and IMPS all operate 24x7x365."
        ],
        quickRevision: "NEFT = RBI, 30-min batches, no minimum limit. RTGS = RBI, real-time gross, MINIMUM ₹2,00,000. IMPS = NPCI, instant, max ₹5 Lakh. All operate 24x7x365."
      },
      {
        code: "8.7",
        title: "BBPS and Safe Digital Banking Practices",
        whatIsIt: "BBPS (Bharat Bill Payment System) is an integrated ecosystem managed by NPCI for paying utility bills (electricity, water, gas, DTH, telecom) under a single trusted platform. Safe digital banking practices are security protocols that protect accounts from cyber fraud.",
        whyImportant: "Cybercriminals use social engineering, phishing, and fake calls to steal life savings. Strictly adhering to safe banking rules prevents financial loss.",
        howItWorks: "BBPS connects billers with payment platforms via NPCI Bharat BillPay Limited (NBBL). Safe banking practices enforce two-factor authentication and secrecy of credentials.",
        componentsTitle: "GOLDEN RULES OF SAFE DIGITAL BANKING",
        componentsOrTypes: [
          "NEVER Share Secret Credentials: Never disclose your OTP, UPI PIN, ATM PIN, Card CVV, or Net Banking Password to anyone - not even bank officials or police.",
          "Bank Officials Never Solicit Secrets: Legitimate bank employees will NEVER call, message, or email asking for your password, PIN, or OTP.",
          "Do Not Install Remote Desktop Apps: Fraudsters ask victims to install remote sharing tools (e.g. AnyDesk, TeamViewer, QuickSupport) under the guise of 'KYC verification' to view OTPs and drain accounts.",
          "Verify Sender IDs: Only trust official banking SMS shortcodes (e.g., `SBIINB`, `HDFCBK`), not regular 10-digit mobile numbers.",
          "National Cyber Crime Reporting Helpline: If you fall victim to financial cyber fraud, immediately report it to the national helpline by dialing **`1930`** or visiting `cybercrime.gov.in`."
        ],
        practicalExample: "You receive a phone call claiming: 'Your electricity connection will be disconnected tonight. Install this APK app and pay ₹10 to update your bill.' This is a classic phishing scam. A cyber-smart citizen ignores the caller, opens their trusted BHIM or banking app, and checks their actual bill via BBPS safely.",
        importantPoints: [
          "BBPS stands for Bharat Bill Payment System, operated by NPCI / NBBL.",
          "Never enter your UPI PIN to receive money or cashback.",
          "Bank employees NEVER ask for OTP, PIN, or CVV.",
          "National Cyber Crime Reporting Helpline number is 1930."
        ],
        quickRevision: "BBPS (NPCI) unifies utility bill payments. Never share OTP, PIN, or CVV. Banks never ask for passwords. Report cyber fraud immediately to National Helpline 1930."
      }
    ],
    unitRevision: [
      "Digital Authentication: OTP (One Time Password, single use, 5-10 min expiry) and QR Code (Denso Wave 1994, 2D matrix with 3 corner squares, 30% error correction).",
      "UPI (Unified Payments Interface, NPCI 2016) operates 24x7 via Virtual Payment Address (VPA).",
      "GOLDEN RULE OF UPI: UPI PIN is required ONLY to send money or check balance, NEVER to receive money.",
      "BHIM App (Bharat Interface for Money) was launched on 30 December 2016, named in honor of Dr. B.R. Ambedkar.",
      "AEPS (Aadhaar Enabled Payment System, NPCI) enables cardless banking via Bank Mitras using a 12-digit Aadhaar number + Biometric fingerprint/iris.",
      "USSD Banking (*99#, NUUP by NPCI) operates on basic 2G feature phones with NO internet across 13 Indian languages using 7-digit MMID.",
      "Payment Cards: 16-digit card number, 3-digit CVV on back signature strip. Debit = pay now; Credit = pay later. RuPay is India's domestic card network (NPCI 2012).",
      "Electronic Fund Transfers: NEFT (RBI, 30-min batches, no minimum), RTGS (RBI, MINIMUM ₹2,00,000, real-time gross), IMPS (NPCI, instant, max ₹5 Lakh). All run 24x7.",
      "BBPS (Bharat Bill Payment System, NPCI) provides unified utility bill payments.",
      "Never share OTP, PIN, or CVV. National Cyber Crime Helpline number is 1930."
    ],
    keyTerms: [
      { term: "NPCI", fullForm: "National Payments Corporation of India", desc: "Umbrella organization for retail payment and settlement systems in India." },
      { term: "UPI", fullForm: "Unified Payments Interface", desc: "Real-time payment system developed by NPCI facilitating inter-bank peer-to-peer transactions." },
      { term: "BHIM", fullForm: "Bharat Interface for Money", desc: "Official Indian mobile payment app developed by NPCI using UPI." },
      { term: "VPA", fullForm: "Virtual Payment Address", desc: "Unique financial identifier (e.g. name@upi) used in UPI transactions." },
      { term: "AEPS", fullForm: "Aadhaar Enabled Payment System", desc: "Bank-led biometric financial inclusion model operated via Micro-ATMs." },
      { term: "USSD", fullForm: "Unstructured Supplementary Service Data", desc: "GSM cellular communications protocol used for *99# mobile banking." },
      { term: "NUUP", fullForm: "National Unified USSD Platform", desc: "NPCI's telecom platform powering *99# USSD mobile banking." },
      { term: "MMID", fullForm: "Mobile Money Identifier", desc: "7-digit random number issued by banks for mobile funds transfer." },
      { term: "CVV", fullForm: "Card Verification Value", desc: "3-digit security code printed on the signature strip on the back of payment cards." },
      { term: "NEFT", fullForm: "National Electronic Funds Transfer", desc: "Nationwide funds transfer system maintained by RBI settling in half-hour batches." },
      { term: "RTGS", fullForm: "Real Time Gross Settlement", desc: "Continuous gross settlement system for high-value transfers (minimum ₹2,00,000)." },
      { term: "IMPS", fullForm: "Immediate Payment Service", desc: "Instant 24x7 inter-bank electronic fund transfer service managed by NPCI." },
      { term: "BBPS", fullForm: "Bharat Bill Payment System", desc: "Unified interoperable bill payment platform operated by NPCI/NBBL." }
    ]
  };
}
